### ISSUE TITLE
校验结果和交互效果不一致，校验逻辑我才改了这几个地方可以正常生效

### ISSUE THREAD

**Issue by sunxia628** [shengxinjing/vue-master-lesson#1]
01\src\App.vue
      submitForm(form) {
        this.$refs[form].validate(valid=>{
          console.log('valid:', valid)
          if (!valid) {
            alert('请求登录!')
          } else {
            alert('校验失败！')
          }
        })
      }
01\src\components\KForm.vue
      Promise.all(tasks)
        .then(() => cb(tasks ? tasks.join('') : tasks))
        .catch(() => cb(true));
01\src\components\KFormItem.vue
            validate() {
               // 返回校验结果
                return this.error
            }
校验结果和交互效果不一致，校验逻辑我才改了这几个地方可以正常生效

**Comment by clannadx** [comment]
不行吧

**Comment by sunxia628** [comment]
可以的你再试一下，这个文件你要确认一下，有多个目录

**Comment by sunxia628** [comment]
> 不行吧

可以的你再试一下，这个文件你要确认一下，有多个目录

**Comment by clannadx** [comment]
嗯嗯 
```javascript
      Promise.all(tasks)
        .then(() => cb(tasks.join("")? false :true ))
        .catch(() => cb(false));
``` 
我这样写的

**Comment by shengxinjing** [comment]
修了
